FreeBSD and clang support
Barracuda09/SATPI pull request #104
Opened 2020-11-23 11:56 UTC by decke

To properly compile SATPI on FreeBSD 12.2/amd64 with the default compiler clang 10 I had to make some adjustments. This are the hopefully non controversial parts of these changes. The compiler output leading to the changes are in the commit logs.

I have also done a test build with those changes on Alpine Linux (musl) with gcc 9.3.0.

2020-11-23 13:20 UTC, Barracuda09 requested changes
Hi,

Those function are 'static constexpr functions' but only used as member functions. So the solutions should be more like:
`static constexpr std::size_t size = mpegts::PacketBuffer::getNumberOfTSPackets()`

2020-11-24 10:47 UTC, Barracuda09 requested changes
Hi,

Maybe use something like this:
```
#ifndef HAS_NP_FUNCTIONS
#include <sys/prctl.h>
#endif
```
Because during make it will try to find out if `xxx_np` functions exists and `HAS_NP_FUNCTIONS` is set. So this include is only needed when `xxx_np` functions do NOT exist. That is if FreeBSD always have these functions. Some linux distro do not have them and have this `prctl` as "backup".

So the change depends on this assumption that FreeBSD always have these function. If not there will be a compile error were the `prctl` is used, either way. So then there should be made a more robust fix.

2020-11-25 12:45 UTC, decke commented
That seems valid for FreeBSD since pthread NP functions always exist (at least on all supported releases).

2020-11-25 13:28 UTC, decke commented
It seems I spoke too soon. Most of the NP functions exist much longer but especially pthread_getname_np() and pthread_setname_np() were added around 5 months ago and only made it to FreeBSD 12.2 yet.

https://svnweb.freebsd.org/base?view=revision&revision=362264

The result is the same though. We don't have sys/prctl.h at all so FreeBSD 12.2 is the minimum version required to build SATPI.

2020-11-25 19:16 UTC, Barracuda09 commented
@decke 

So alternative, the naming of a thread should not be use in FreeBSD below 12.2. Or does there exist other ways of doing this?

2020-11-25 19:23 UTC, Barracuda09 commented
The `pthread_set_name_np` is around since FreeBSD 4.8 but it is in include file `<pthread_np.h>`

https://www.freebsd.org/cgi/man.cgi?query=pthread_set_name_np&apropos=0&sektion=3&manpath=FreeBSD+4.8-RELEASE&arch=default&format=html

Maybe that is the problem?

2020-11-25 19:35 UTC, decke commented
Yes, there are other similar functions available but honestly I don't know yet what else might be missing on FreeBSD 11.4. On 12.2 all pthread np functions exist which are currently used. So my focus is first to make it all work on 12.2 and only then take care of older FreeBSD versions.

2020-11-26 07:45 UTC, Barracuda09 approved these changes
These changes seems Okey to me now. Will try to test tonight, if it compiles in my situation.

Thanks for you support

2020-11-26 19:29 UTC, merged